[alembic]
# path to migration scripts
script_location = alembic

# the template used to generate migration files
# file_alembic_template = %(alembic)s/versions/%(rev)s_%(slug)s

# sys.path path, will be prepended to sys.path if present.
# defaults to the current working directory.
prepend_sys_path = .
version_path_separator = ;

# The version table name to be used in the database.
#version_table = alembic_version

# If set to 'True', run the environment during
# the 'revision' command, regardless of autogenerate.
# revision_environment = false
# If set to 'True', the version table name can be overridden with
# the command line option '-x version_table=<name>'.
# version_table_name = False
# The output encoding used when revision files are written from code
# (assuming they are Unicode).
# output_encoding = utf-8

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(asctime)s,%(msecs)03d %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S